implement read trait for assets for full reader functionality
eluv-io/elv_wasm pull request #24
Opened 2024-12-24 21:16 UTC by JanFalkin

2025-01-08 13:54 UTC, lukseven commented on src/bccontext_fabric_io.rs
> +pub struct FabricSteamReader<'a> {
I hope this is just a typo...
```suggestion
pub struct FabricStreamReader<'a> {
```

2025-01-13 20:41 UTC, elv-nate approved these changes
Some notes on this. It seems reasonable on the whole. I didn't have a ton of time to dedicate to the review, however..

2025-01-13 20:41 UTC, elv-nate commented on src/bccontext_fabric_io.rs
> +    fn seek(&mut self, pos: SeekFrom) -> Result<u64, std::io::Error> {
This should just error, right?

2025-01-13 20:41 UTC, elv-nate commented on src/bccontext.rs
> -    pub fn read_stream_chunked(&'a self, stream_to_read: String, chunk_size: usize) -> CallResult {
Document on `read_stream` that setting a size of 0 results in the _entire_ stream being read into memory at once.

2025-03-04 01:24 UTC, elv-nate requested changes

2025-03-04 01:24 UTC, elv-nate commented on src/bccontext_fabric_io.rs
> +            Ok(_) => Ok(0),
This is wrong. From `std::io::Seek` docs: 

If the seek operation completed successfully, this method returns the new position from the start of the stream. That position can be used later with [SeekFrom::Start](https://doc.rust-lang.org/beta/std/io/enum.SeekFrom.html#variant.Start).

2025-03-04 01:24 UTC, elv-nate commented on samples/objtar/src/lib.rs
> +        fsr.seek(SeekFrom::Start(pos))?;
Validate this return value.

2025-03-04 18:08 UTC, elv-nate approved these changes
Looks like it should be reasonable now

2025-03-04 18:08 UTC, elv-nate commented on src/bccontext_struct.rs
> +/// Bitcode representation of a fabric size error
Copied comment should be adjusted

2025-03-05 17:21 UTC, merged